function [qpoints,DynaMat_full]=Read_DynMat_QE_in_individual_files_from_ph_calculation(number_of_individual_files,filename_dynmat_with_index,nat,amass)
% The copyright by Van-Truong TRAN.
% Code version: V1.0 (01/2022)


% READING Dynamical matrix file generated by QE calculation
% number_of_individual_files: number of files .dyn1, .dyn2, ... contains
% force constants generated from ph.x calculations
% filename_dynmat: name of the system: file data is "prefix.dynmat". Format: string
% nat: number of atoms in the unit cell in QE calculation. Format: integer
% amass: atomic mass of each kind of atoms. Format: real



qpoints=[];
for n_f=1:number_of_individual_files

prefix_n_f=sprintf('%s%d',filename_dynmat_with_index,n_f);%'PbTe.dynmat';

% read dynamic matrix file: prefix.dynmat
[qpoints_n_f,DynaMat_full_n_f]=Read_DynMat_QE(prefix_n_f,nat,amass);


N_q_0=size(qpoints,1);

%qpoints=[qpoints;qpoints_n_f];

for i=1:size(qpoints_n_f,1)
qpoints(N_q_0+i,1:3)=qpoints_n_f(i,:);
DynaMat_full{N_q_0+i}=DynaMat_full_n_f{i};

% qpoints_n_f(i,:)
% DynaMat_full_n_f{i}

end

end


